[manifest]
id = "fast_boot"
version = "1.0.0"
display_name = "Fast Boot"
description = "Boots to the main menu much faster than otherwise"
short_description = "Boots to the main menu much faster than otherwise"
authors = [ "Ballaam", "Bismuth" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "fast_boot"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
